//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfClima.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clima
    {
        public int idCiudad { get; set; }
        public System.DateTime fecha { get; set; }
        public int temperatura { get; set; }
        public int humedad { get; set; }
        public int precipitacion { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
    }
}
